### ISSUE TITLE
Find all low level logging statements

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#1]
To find logging statements, we must start with finding all instances of log.*.Msg(someString)

**Comment by RussellSanders1** [comment]
Recursively backtracked from Msg calls to verify they originate from a log statement, collected resulting nodes for information extraction (see #2)

**Comment by vinbush** [comment]
Going to close this issue, since it appears to be finding most of the logging statements, we can open new issues if we find gaps in our coverage.
