### ISSUE TITLE
Create DAO function to connect 2 existing nodes

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#19]
Given two nodes, use their line numbers and filenames to create a relationship between them in Neo4j

**Comment by RussellSanders1** [comment]
DAO function should be working, though I don't know how to test it honestly.  This would fit nicely in the callFrom() function iside the parseProject handler, but that package does not handle Nodes from neo4j, so it may be prudent to refactor this function to take different parameters that could be generated from the callFrom() function.

**Comment by RussellSanders1** [comment]
Going ahead with adapting function idea, and also going to implement another child for function calls that will allow for the connection of return statements to the statement immediately following the function call

**Comment by RussellSanders1** [comment]
Scrapped additional child Node idea, not necessary, just used Neo4j queries to find the Nodes desired and recreated/deleted their appropriate relationships.  Only thing left is to consider the addition of feedback from the function besides error, possibly making the changes in the graph accessible as a tree in-memory.

note: one additional test-case I did not conceive was the connection of the last statement in a function to the first of another.
