### ISSUE TITLE
Find all log strings

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#2]
Once we have all log.*.Msg(string) instances, we have to track where they are called, and find all the possible strings that could be passed into it.

**Comment by RussellSanders1** [comment]
Extracted the filename, line number, and message string of Msg calls (see #3 for how to handle Msgf calls for real regex extraction)

**Comment by RussellSanders1** [comment]
Note: Messages with const assigned in another file seems to break extraction, probably an unhandled type error

**Comment by RussellSanders1** [comment]
Additional note: strings may be assigned through the use of fmt.Sprint* functions, so some kind of mining for the assigned data will need to be implemented.  Unsure how many ways there are to assign variables at this point, may need to consider generic approaches to avoid growing number of cases

**Comment by vinbush** [comment]
You are right, there are many ways that a string could get formed. fmt.Sprint* functions appear to be the most common way I've seen in my 5 days of Go experience, so I think that suffices for now.
