### ISSUE TITLE
Add var nodes to the tree

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#45]
At parse time, variable nodes need to be added when they are encountered. If the variable gets its value from a function, then it should come after that function in the tree, with something indicating this is the case in this node.

**Comment by vinbush** [comment]
@mdu2017 The variable nodes need a boolean flag to check if they get their value from their parent call function. The parent cannot be nil since we need to be able to traverse up through the parent, even if it doesn't get its value from it.

**Comment by mdu2017** [comment]
If there are multiple variables that get their value from the same parent (function), do both of the variable nodes need to link to the same parent? Currently the function nodes only support having a pointer to one child, so one option could be to link together a list of variable nodes, or another option could be where the function node points to a struct containing a list of variable nodes.
The var nodes currently have the variable name/type/expression information, but I'm not sure exactly how to add the nodes to the CFG.

**Comment by vinbush** [comment]
Are you talking about the case of x, y = funcCall()? In that case, just
make it a chain of variable statements, one after the next. It actually
works out because we need to have them in a specific order (left to right)
