### ISSUE TITLE
Add parameters and arguments to function nodes and function declaration nodes

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#48]
The FunctionNode and FunctionDeclNode need to include a list of parameters/arguments. These should include the scope name and variable name.

```
// function calls have list of arguments
{FunctionNode, calledFunc, [{scope: outerFunc.1, varname: x}, {scope: outerFunc.1, varname: y}]}
// function decls have list of parameters
{FunctionDeclNode, someFunc, [{scope: someFunc, varname: a}, {scope: someFunc, varname: b}]}
```

**Comment by RussellSanders1** [comment]
changing params in FunctionDeclNode to a map[int]Variable, where the int will be used to denote the ordering of the parameter variables so we can ensure strict ordering.  The same will be applied to a new Args member in FunctionNode, so the two will be associated by the same map index

**Comment by RussellSanders1** [comment]
Variable is a new struct containing Scope and Name strings
