### ISSUE TITLE
Find log messages originating in different files

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#7]
If a log.something().Msg() message is wrapped in a function, and that function's argument is used as the log message, we need to find the possible original values of that argument.

**Comment by vinbush** [comment]
For example, in [consumer > processing.go, line 101](https://github.com/RedHatInsights/insights-results-aggregator/blob/bd7479e90b247819b3cfed0566fb289910fdbbab/consumer/processing.go#L101), we have `logUnparsedMessageError(consumer, msg, "Error parsing message from Kafka", err)`, which is defined as:
```
func logUnparsedMessageError(consumer *KafkaConsumer, originalMessage *sarama.ConsumerMessage, event string, err error) {
	log.Error().
		Int(offsetKey, int(originalMessage.Offset)).
		Str(topicKey, consumer.Configuration.Topic).
		Err(err).
		Msg(event)
}
```
So we need to identify "Error parsing message from Kafka" as a possible log type.

@RussellSanders1 Is this related to the const issue you mention in #2? I.e. is that error caused by the string being in another file, or by being a const?

**Comment by RussellSanders1** [comment]
This has to do with our discussion on finding function calls and log wrappers, but the event "Error parsing message from kafka" is a literal and will be easy to extract once we have traced to this instance of the function

**Comment by vinbush** [comment]
Adding @mdu2017 to this issue, as discussed today
