### ISSUE TITLE
Find messages in Err()

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#8]
If an error is logged, it can generate multiple messages in the parsed output we receive: one message is logged with the `Err()` function, and another with the `Msg()` function (both on the `log` object). We should identify both of these messages.

For example, in the parsed output from Jan's team, we have:
```
"messages": [
    ...
    [
        "error",
        "2020-03-17T11:33:07Z",
        "Error parsing message from Kafka"
    ],
    [
        "error",
        "2020-03-17T11:33:07Z",
        "missing required attribute 'ClusterName'"
    ],
    ...
],
```
Both of these error messages come from the same statement:
```
logUnparsedMessageError(consumer, msg, "Error parsing message from Kafka", err)
// implementation:
func logUnparsedMessageError(consumer *KafkaConsumer, originalMessage *sarama.ConsumerMessage, event string, err error) {
	log.Error().
		Int(offsetKey, int(originalMessage.Offset)).
		Str(topicKey, consumer.Configuration.Topic).
		Err(err). // one message comes from here
		Msg(event) // another from here
}
```
with err being determined by:
```
message, err := parseMessage(msg.Value)
...
func parseMessage(messageValue []byte) (incomingMessage, error) {
	// other stuff
	if deserialized.Organization == nil {
		return deserialized, errors.New("missing required attribute 'OrgID'")
	}
	if deserialized.ClusterName == nil {
		return deserialized, errors.New("missing required attribute 'ClusterName'")
	}
	if deserialized.Report == nil {
		return deserialized, errors.New("missing required attribute 'Report'")
	}
        // other stuff
}
```

**Comment by RussellSanders1** [comment]
Looking through docs for zerolog, Err and Msg are in fact the only calls that accept msg values, but in the future, it may be prudent to also parse calls to Int, or Str, because this data is stored as key-value pairs just like the message and error, so in future development this may become useful once variable information is being considered.
