### ISSUE TITLE
Build SMT solver calls

### ISSUE THREAD

**Issue by RussellSanders1** [cloudhubs/sourcecrawler#85]
We should be able to write a function that traverses an IfStmt node from the AST, and using the token.Token types of the operators, call the appropriate z3 functions to construct the constraints.  I will post a simple sample as soon as I can.

**Comment by nnazo** [comment]
I was actually working on this up until just a minute ago since I have had it working. I just pushed what I had so far to the `smt-conditions` branch.

**Comment by RussellSanders1** [comment]
@nnazo did it seem to be working?  I can't exactly test without z3 set up, but this looks exactly like what I was planning in my head, so if it works, that's great.

**Comment by nnazo** [comment]
I haven't written any tests for it yet to see since I was just getting an initial version written up, but I'll try and write some simple tests to see.

**Comment by nnazo** [comment]
I'm not comparing the output in the tests yet since I'm just trying to get it running properly first, and for some reason the test case is unsolvable even though it's the same as the go-z3 example

**Comment by RussellSanders1** [comment]
Okay, good to note. It seems like once we figure out ho to build the AST for z3 extensively, we should just be able to create and assert one for every condition we encounter in the path, then afterward we can get the model and assignments, if I understand correctly.  I'm not sure how we will handle reassignment of a variable, since it seems that would probably contradict any previous assertions, unless they are evaluated in-order.
