### ISSUE TITLE
Rewrite /slice endpoint to use the new CFG/SMT functions

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#89]
This endpoint should take the stack trace and messages and build the CFG/analyze the paths using our reworked functionality.

**Comment by RussellSanders1** [comment]
Label functionality needs to implement log matching and stack trace.

@mdu2017 can you add this?

**Comment by RussellSanders1** [comment]
How to find the block that represents the Panic thrown?  This will be a good base to start labeling, since we don't care about anything else.  Not sure how this is represented
