### ISSUE TITLE
Create equality conditions for reassignments

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#90]
If a variable gets reassigned, then there needs to be a condition in the path indicating the new value. I.e. if you have
x = x * 2
There needs to be a condition for that in the path, with the correct SSA variables names (so if we are on 4x, then it would be):
5x = 4x * 2

**Comment by nnazo** [comment]
I have these changes up on the `smt-conditions` branch. I added an extra test case for this, and it also seems to be working with the original test case we've been using.

It also works with shorthand reassignments such as `+=`, `++` etc. by creating its non-shorthand form and using that node for the SMT solver instead.
