### ISSUE TITLE
Integrate labeling feature with rewrite functions/slice endpoint

### ISSUE THREAD

**Issue by mdu2017** [cloudhubs/sourcecrawler#94]
Working on adding functionality to do log matching via regex and using the stack trace. Will add to the slice endpoint once completed.
Note: Running the endpoint in a docker container causes Postman request issues since the host can't access the app from outside the container. (Most likely requires some docker-compose configuration)

**Comment by RussellSanders1** [comment]
Need to integrate labeling functionality with the traverseCFG function in order to limit the paths gathered by the function

**Comment by RussellSanders1** [comment]
Actually, if starting from the exception, this is not necessary. Postponing any further work on that.

**Comment by mdu2017** [comment]
Fixed bugs with the returned logTypes in ParseProject: (this is used in the labeling to match logging statements via regex)
 -Duplicate log entries
 -Not finding all log statements (originally only finding zerolog functions that had Msg/Msgf, but should now work with the basic go log library functions, ex: log.println(), log.print())
 -Empty filepath
 
Passed stack trace info to check if a particular FnWrapper is labeled Must/May
Added regex matching in the label functionality (should be in CheckLogStatus)
Changing the return on parse panic to be a single stackTraceStruct

Note: Seems a bit slow when debugging, may need some cleanup for repeated work later. Had to fix a lot of bugs from the old functions and refactor some files to fix a dependency issue.

-Bug with first constraint not being labeled, need to add labels onto each constraint and test
